### ISSUE TITLE
HasClusterID() and allow-untagged-cloud

### ISSUE THREAD

**Issue by guettli** [kubernetes/cloud-provider#71]
Looking at the basic_main.go

```Go
	if !cloud.HasClusterID() {
		if config.ComponentConfig.KubeCloudShared.AllowUntaggedCloud {
			klog.Warning("detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues")
		} else {
			klog.Fatalf("no ClusterID found.  A ClusterID is required for the cloud provider to function properly.  This check can be bypassed by setting the allow-untagged-cloud option")
		}
	}
```

[basic_main.go](https://github.com/kubernetes/cloud-provider/blob/0d9387a3762c9b8e20c6f0af0afb5f2743a4896c/sample/basic_main.go#L90)

But where is ClusterID actually used?

Afaik allow-untagged-cloud is deprecated, but afaik ClusterID does not get used.

The current state is confusing.

Please explain how a ccm should implement a ClusterID.

**Comment by elmiko** [comment]
we are discussing this issue today at the sig cloud provider meeting, it seems like this is a good research topic for understand how the ClusterID is being used.

one point of order @guettli , would you mind opening this issue against kubernetes/kubernetes so that we can link the work to any changes that might need to be made there. (this repo is sync from the staging)

**Comment by guettli** [comment]
@elmiko I am in hospital at the moment. Can you please create the other issue?

**Comment by elmiko** [comment]
i have created https://github.com/kubernetes/kubernetes/issues/128320 , let's continue the discussion there. thanks for reporting this @guettli !
